name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull "${{ secrets.DOCKERHUB_USER }}"/golang-orders:latest

      - name: Run Container on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker stop golang-orders || true
            docker rm golang-orders || true
            docker pull "${{ secrets.DOCKERHUB_USER }}"/golang-orders:latest
            docker run -d -p 8000:8000 --name golang-orders "${{ secrets.DOCKERHUB_USER }}"/golang-orders:latest
